# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  default:
    deps: [check]

  check:
    - task: tests
    - task: type
    - task: lint
    - task: fmtchk
    - git diff --exit-code

  fix: "{{.RUN}} ruff check --fix {{.CLI_ARGS}}"
  fmt: "{{.RUN}} ruff format {{.CLI_ARGS}}"
  fmtchk: "{{.RUN}} ruff format --check {{.CLI_ARGS}}"
  lint: "{{.RUN}} ruff check {{.CLI_ARGS}}"
  test: "{{.RUN}} pytest tests {{.PYTEST}} {{.CLI_ARGS}}"
  tests: "{{.RUN}} tox {{.TOX}} {{.CLI_ARGS}}"
  type: "{{.RUN}} ty check {{.TY}} {{.CLI_ARGS}}"

  gen:
    - "{{.RUN}} unicodedata-reader lb -t js/template.js {{.GEN}} {{.CLI_ARGS}}"
    - "{{.RUN}} unicodedata-reader gc -t js/template.js {{.GEN}} {{.CLI_ARGS}}"

  install-git-hooks:
    desc: Create git hooks
    cmds:
      - echo '#!/bin/sh' > .git/hooks/pre-push
      - echo 'task check' >> .git/hooks/pre-push
      - cmd: chmod +x .git/hooks/pre-push
        platforms: [linux, darwin]

vars:
  GEN: -fv
  PYTEST:
  RUN: uv run
  TOX: -p
  TY:
