name: Publish

# Controls when the action will run.
on:
  release:
    types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # https://docs.astral.sh/uv/guides/integration/github/
      - name: Install uv and set up Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          uv sync --all-extras --dev

      - name: Build and publish
        run: |
          uv publish --build
